name: hello world 

on:
  push:
    branches:
    - master

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
      - run: pwd
      - run: ls -al
      - run: ./hello.sh
