name: hello world 

on:
  push:
    branches:
    - master

jobs:
  Explore-GitHub-Actions:
    #runs-on: ubuntu-latest
    runs-on: Linux
    steps:
      - run: echo "hello world"
      - run: cd /home && pwd && ls -al
      - run: pwd && ls -al
        #- run: ./hello.sh
